In [41]:
import json
import math
import os
import numpy as np
import pandas as pd
from collections import defaultdict, Counter

# Import the ManualNaiveBayes class and utility functions from the new file
from manual_naive_bayes_utils import ManualNaiveBayes, train_test_split as manual_train_test_split # Use alias for manual split


# ========== Load Processed Data ==========
print("Loading processed data...")

# Load the document metadata and TF-IDF vectors
try:
    with open("indexes/document_metadata.json", "r", encoding="utf-8") as f:
        document_metadata = json.load(f)

    with open("indexes/tfidf_vectors_sklearn.json", "r", encoding="utf-8") as f:
        tfidf_vectors = json.load(f) # This contains document_id: tfidf_vector_list

    with open("indexes/vocabulary_sklearn.json", "r", encoding="utf-8") as f:
        vocabulary = json.load(f) # Loading the pre-built vocabulary

except FileNotFoundError as e:
    print(f"Error loading data files: {e}")
    print("Please ensure 'indexes/document_metadata.json', 'indexes/tfidf_vectors_sklearn.json', and 'indexes/vocabulary_sklearn.json' exist.")
    # Exit or handle the error appropriately if files are not found
    raise e


# ========== Prepare Data with Specific Indices ==========
print("Preparing data with specific indices...")

# 3. Pick PARTICULAR docs (manually set indices instead of random)
# 👉 Modify indices to select a larger subset of data
# indices = list(range(0, len(document_metadata), 5)) # Example: select every 5th document
indices = [
    10, 50, 100, 150, 200, 250, 300, 350, 400, 450,
    500, 550, 600, 650, 700, 750, 800, 850, 900, 950,
    1000, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1450,
    1500, 1550, 1600, 1650, 1700, 1750, 1800, 1850, 1900, 1950
]
# Get document IDs based on the indices
all_doc_ids = list(document_metadata.keys())
# print(all_doc_ids)
selected_doc_ids = [all_doc_ids[i] for i in indices if i < len(all_doc_ids)] # Ensure indices are within bounds

# Extract selected documents and labels
selected_documents = {}
selected_labels = {}
processed_docs_dir = "processed_docs"

print(f"Attempting to load {len(selected_doc_ids)} processed documents based on indices.")
for doc_id in selected_doc_ids:
     try:
        with open(f"{processed_docs_dir}/{doc_id}_processed.json", "r", encoding="utf-8") as f:
            processed_words = json.load(f)
            selected_documents[doc_id] = processed_words
        selected_labels[doc_id] = document_metadata[doc_id][1] # Category is at index 1
     except FileNotFoundError:
         print(f"Warning: Processed document not found for doc_id {doc_id}. Skipping.")
         continue

print(f"Successfully loaded {len(selected_documents)} processed documents.")

# Check class distribution in the selected subset
selected_class_counts = Counter(selected_labels.values())
print("\nClass distribution in selected documents:")
display(pd.DataFrame.from_dict(selected_class_counts, orient='index', columns=['Count']).sort_index())


# # Use the manual train_test_split function on the selected documents
# # This split is applied to the documents successfully loaded based on your indices
# train_documents, test_documents, train_labels_dict, test_labels_dict = manual_train_test_split(
#     selected_documents, selected_labels, test_size=0.2, random_seed=42
# )

# print(f"\nTraining set size: {len(train_documents)} documents")
# print(f"Test set size: {len(test_documents)} documents")
# print(f"Vocabulary size (from indexes/vocabulary_sklearn.json): {len(vocabulary)}")


# # ========== Main Execution: Train and Evaluate Manual Naive Bayes ==========
# print("\nTraining Manual Naive Bayes classifier...")
# # Pass the loaded vocabulary to the classifier
# nb_classifier = ManualNaiveBayes(vocabulary)
# nb_classifier.train(train_documents, train_labels_dict)

# # Evaluate on test data
# results = nb_classifier.evaluate(test_documents, test_labels_dict)

# print(f"\n=== MANUAL NAIVE BAYES EVALUATION ===")

# # Create a DataFrame for overall metrics
# overall_metrics = {
#     'Model': ['Manual Naive Bayes'],
#     'Accuracy': [results['accuracy']],
#     'Precision': [np.mean([m['precision'] for m in results['class_metrics'].values()]) if results['class_metrics'] else 0],
#     'Recall': [np.mean([m['recall'] for m in results['class_metrics'].values()]) if results['class_metrics'] else 0],
#     'F1-Score': [np.mean([m['f1'] for m in results['class_metrics'].values()]) if results['class_metrics'] else 0]
# }
# overall_metrics_df = pd.DataFrame(overall_metrics)
# display(overall_metrics_df.round(4))

# print(f"\n=== MANUAL NAIVE BAYES PER-CLASS METRICS ===")
# if results['class_metrics']:
#     class_metrics_list = []
#     # Sort metrics by class label for consistent display
#     for class_label in sorted(results['class_metrics'].keys()):
#         metrics = results['class_metrics'][class_label]
#         class_metrics_list.append({
#             'Class': class_label,
#             'Precision': metrics['precision'],
#             'Recall': metrics['recall'],
#             'F1-score': metrics['f1'],
#             'Support': metrics['support']
#         })
#     class_metrics_df = pd.DataFrame(class_metrics_list)
#     display(class_metrics_df.round(4))
# else:
#     print("No class metrics to display.")

# print("\n=== MANUAL NAIVE BAYES SAMPLE PREDICTIONS ===")
# if results['predictions']:
#     sample_predictions = []
#     # Sort predictions by filename for consistent display
#     for filename, true_label, predicted_label in sorted(results['predictions'][:10]): # Display first 10 predictions, sorted by filename
#         status = "✓" if true_label == predicted_label else "✗"
#         sample_predictions.append({
#             'Status': status,
#             'Filename': filename,
#             'True Label': true_label,
#             'Predicted Label': predicted_label
#         })
#     sample_predictions_df = pd.DataFrame(sample_predictions)
#     display(sample_predictions_df)
# else:
#     print("No predictions to display.")


# print("\n=== COMPARISON WITH MANUAL NAIVE BAYES ===")
# print("Manual Naive Bayes Results (from above output):")
# # Display the results DataFrames that were just created
# print("\nManual Naive Bayes Overall Metrics:")
# display(overall_metrics_df.round(4))
# print("\nManual Naive Bayes Per-Class Metrics:")
# display(class_metrics_df.round(4))

Loading processed data...
Preparing data with specific indices...
Attempting to load 40 processed documents based on indices.
Successfully loaded 40 processed documents.

Class distribution in selected documents:

                          Count
alt.atheism                   2
comp.graphics                 2
comp.os.ms-windows.misc       2
comp.sys.ibm.pc.hardware      2
comp.sys.mac.hardware         2
comp.windows.x                2
misc.forsale                  2
rec.autos                     2
rec.motorcycles               2
rec.sport.baseball            2
rec.sport.hockey              2
sci.crypt                     2
sci.electronics               2
sci.med                       2
sci.space                     2
soc.religion.christian        2
talk.politics.guns            2
talk.politics.mideast         2
talk.politics.misc            2
talk.religion.misc            2

Training set size: 32 documents
Test set size: 8 documents
Vocabulary size (from indexes/vocabulary_sklearn.json): 10000

Training Manual Naive Bayes classifier...

=== MANUAL NAIVE BAYES EVALUATION ===

                Model  Accuracy  Precision  Recall  F1-Score
0  Manual Naive Bayes       0.0        0.0     0.0       0.0

=== MANUAL NAIVE BAYES PER-CLASS METRICS ===

                      Class  Precision  Recall  F1-score  Support
0  comp.sys.ibm.pc.hardware          0     0.0         0        1
1            comp.windows.x          0     0.0         0        1
2                 rec.autos          0     0.0         0        1
3        rec.sport.baseball          0     0.0         0        1
4          rec.sport.hockey          0     0.0         0        1
5                 sci.crypt          0     0.0         0        1
6                 sci.space          0     0.0         0        1
7        talk.religion.misc          0     0.0         0        1

=== MANUAL NAIVE BAYES SAMPLE PREDICTIONS ===

,Status,Filename,True Label,Predicted Label
0,✗,comp.sys.ibm.pc.hardware_doc0050,comp.sys.ibm.pc.hardware,comp.graphics
1,✗,comp.windows.x_doc0000,comp.windows.x,sci.electronics
2,✗,rec.autos_doc0000,rec.autos,talk.politics.misc
3,✗,rec.sport.baseball_doc0000,rec.sport.baseball,sci.electronics
4,✗,rec.sport.hockey_doc0000,rec.sport.hockey,alt.atheism
5,✗,sci.crypt_doc0000,sci.crypt,sci.electronics
6,✗,sci.space_doc0000,sci.space,sci.electronics
7,✗,talk.religion.misc_doc0000,talk.religion.misc,soc.religion.christian

=== COMPARISON WITH MANUAL NAIVE BAYES ===
Manual Naive Bayes Results (from above output):

Manual Naive Bayes Overall Metrics:

                Model  Accuracy  Precision  Recall  F1-Score
0  Manual Naive Bayes       0.0        0.0     0.0       0.0

Manual Naive Bayes Per-Class Metrics:

                      Class  Precision  Recall  F1-score  Support
0  comp.sys.ibm.pc.hardware          0     0.0         0        1
1            comp.windows.x          0     0.0         0        1
2                 rec.autos          0     0.0         0        1
3        rec.sport.baseball          0     0.0         0        1
4          rec.sport.hockey          0     0.0         0        1
5                 sci.crypt          0     0.0         0        1
6                 sci.space          0     0.0         0        1
7        talk.religion.misc          0     0.0         0        1

In [47]:
import json
import os
from collections import defaultdict, Counter
import pandas as pd

chosen_categories = ['comp.graphics', 'sci.space', 'rec.sport.baseball', 
                     'talk.politics.mideast', 'alt.atheism']
# ========== Load Processed Data ==========
print("Loading processed data...")

try:
    with open("indexes/document_metadata.json", "r", encoding="utf-8") as f:
        document_metadata = json.load(f)

    with open("indexes/tfidf_vectors_sklearn.json", "r", encoding="utf-8") as f:
        tfidf_vectors = json.load(f) 

    with open("indexes/vocabulary_sklearn.json", "r", encoding="utf-8") as f:
        vocabulary = json.load(f)

except FileNotFoundError as e:
    print(f"Error loading data files: {e}")
    raise e


# ========== Prepare Data with Specific Indices ==========
print("Preparing data with specific indices...")

indices = [
     0,  2,  4,  6,  8,
    10, 12, 14, 16, 18,
    20, 22, 24, 26, 28,
    30, 32, 34, 36, 38,
    40, 42, 44, 46, 48,
    50, 52, 54, 56, 58,
    60, 62, 64, 66, 68,
    70, 72, 74, 76, 78
]

all_doc_ids = list(document_metadata.keys())
selected_doc_ids = [all_doc_ids[i] for i in indices if i < len(all_doc_ids)]

selected_documents = {}
selected_labels = {}
processed_docs_dir = "processed_docs"

print(f"Attempting to load {len(selected_doc_ids)} processed documents based on indices.")
for doc_id in selected_doc_ids:
    try:
        with open(f"{processed_docs_dir}/{doc_id}_processed.json", "r", encoding="utf-8") as f:
            processed_words = json.load(f)
            selected_documents[doc_id] = processed_words
        selected_labels[doc_id] = document_metadata[doc_id][1]  # category at index 1
    except FileNotFoundError:
        print(f"Warning: Processed document not found for doc_id {doc_id}. Skipping.")
        continue

print(f"Successfully loaded {len(selected_documents)} processed documents.")


# ========== Class Distribution with Doc IDs ==========
category_to_docs = defaultdict(list)
for doc_id, category in selected_labels.items():
    category_to_docs[category].append(doc_id)

# Build DataFrame
class_distribution = pd.DataFrame([
    {"Category": cat, "Count": len(docs), "Doc_IDs": docs}
    for cat, docs in category_to_docs.items()
]).sort_values(by="Category").reset_index(drop=True)

print("\nClass distribution in selected documents:")
display(class_distribution)

Loading processed data...
Preparing data with specific indices...
Attempting to load 40 processed documents based on indices.
Successfully loaded 40 processed documents.

Class distribution in selected documents:

      Category  Count                                            Doc_IDs
0  alt.atheism     40  [alt.atheism_doc0000, alt.atheism_doc0002, alt...

In [62]:
import json
import os
from collections import defaultdict
import pandas as pd

chosen_categories = ['comp.graphics', 'sci.space', 'rec.sport.baseball', 
                     'talk.politics.mideast', 'alt.atheism']

# ========== Load Processed Data ==========
print("Loading processed data...")

try:
    with open("indexes/document_metadata.json", "r", encoding="utf-8") as f:
        document_metadata = json.load(f)

    with open("indexes/tfidf_vectors_sklearn.json", "r", encoding="utf-8") as f:
        tfidf_vectors = json.load(f) 

    with open("indexes/vocabulary_sklearn.json", "r", encoding="utf-8") as f:
        vocabulary = json.load(f)

except FileNotFoundError as e:
    print(f"Error loading data files: {e}")
    raise e


# ========== Prepare Data with Specific Indices ==========
print("Preparing data with specific indices...")

indices = [
     0,  2,  4,  6,  8,
    10, 12, 14, 16, 18,
    20, 22, 24, 26, 28,
    30, 32, 34, 36, 38,
    40, 42, 44, 46, 48,
    50, 52, 54, 56, 58,
    60, 62, 64, 66, 68,
    70, 72, 74, 76, 78
]

all_doc_ids = list(document_metadata.keys())
selected_doc_ids = [all_doc_ids[i] for i in indices if i < len(all_doc_ids)]

processed_docs_dir = "processed_docs"

# ========== Raw Category Distribution in Selected Indices ==========
debug_counts = defaultdict(list)
for doc_id in selected_doc_ids:
    cat = document_metadata[doc_id][1]
    debug_counts[cat].append(doc_id)

raw_distribution = pd.DataFrame([
    {"Category": cat, "Count": len(docs), "Doc_IDs": docs}
    for cat, docs in debug_counts.items()
]).sort_values(by="Category").reset_index(drop=True)

print("\nRaw distribution in selected indices (before filtering):")
display(raw_distribution)


# ========== Balanced Selection: Up to 5 Per Category ==========
print("\nSelecting up to 5 docs per chosen category from given indices...")

category_to_doc_ids = defaultdict(list)
for doc_id in selected_doc_ids:
    category = document_metadata[doc_id][1]
    if category in chosen_categories:
        category_to_doc_ids[category].append(doc_id)

selected_documents = {}
selected_labels = {}

for category in chosen_categories:
    chosen_ids = category_to_doc_ids[category][:5]  # pick first 5
    for doc_id in chosen_ids:
        try:
            with open(f"{processed_docs_dir}/{doc_id}_processed.json", "r", encoding="utf-8") as f:
                processed_words = json.load(f)
                selected_documents[doc_id] = processed_words
            selected_labels[doc_id] = category
        except FileNotFoundError:
            print(f"Warning: Processed document not found for doc_id {doc_id}. Skipping.")
            continue

print(f"Successfully loaded {len(selected_documents)} processed documents.")


# ========== Final Balanced Distribution ==========
category_to_docs = defaultdict(list)
for doc_id, category in selected_labels.items():
    category_to_docs[category].append(doc_id)

final_distribution = pd.DataFrame([
    {"Category": cat, "Count": len(docs), "Doc_IDs": docs}
    for cat, docs in category_to_docs.items()
]).sort_values(by="Category").reset_index(drop=True)

print("\nFinal balanced distribution (after filtering, max 5 each):")
display(final_distribution)

Loading processed data...
Preparing data with specific indices...

Raw distribution in selected indices (before filtering):

      Category  Count                                            Doc_IDs
0  alt.atheism     40  [alt.atheism_doc0000, alt.atheism_doc0002, alt...

Selecting up to 5 docs per chosen category from given indices...
Successfully loaded 5 processed documents.

Final balanced distribution (after filtering, max 5 each):

      Category  Count                                            Doc_IDs
0  alt.atheism      5  [alt.atheism_doc0000, alt.atheism_doc0002, alt...

In [43]:
import os
import json
from collections import defaultdict
import pandas as pd
from sklearn.datasets import fetch_20newsgroups

# ----- CONFIG: must match whatever you used when you created processed_docs -----
chosen_categories = ['comp.graphics', 'sci.space', 'rec.sport.baseball', 
                     'talk.politics.mideast', 'alt.atheism']
subset = "train"                       # or "all"/"test" — use the same one you processed
remove_parts = ('headers','footers','quotes')  # same preprocessing
shuffle = False                        # IMPORTANT: keep order stable
processed_docs_dir = "processed_docs"

# The 40 global indices you want (all < 100)
indices = [
     0,  2,  4,  6,  8,
    10, 12, 14, 16, 18,
    20, 22, 24, 26, 28,
    30, 32, 34, 36, 38,
    40, 42, 44, 46, 48,
    50, 52, 54, 56, 58,
    60, 62, 64, 66, 68,
    70, 72, 74, 76, 78
]


# ----- 1) Build mapping: global_index -> (category, local_id) -> filename -----
print("Building global_index -> filename mapping from sklearn order...")

ds = fetch_20newsgroups(subset=subset,
                        categories=chosen_categories,
                        remove=remove_parts,
                        shuffle=shuffle)

# per-category running counter to create local ids 0000, 0001, ...
per_cat_counter = defaultdict(int)
global_to_filename = {}
global_to_category = {}

for gidx in range(len(ds.data)):
    cat = ds.target_names[ds.target[gidx]]
    local_id = per_cat_counter[cat]              # 0-based within category
    fname = f"{cat}_doc{local_id:04d}_processed.json"
    global_to_filename[gidx] = fname
    global_to_category[gidx] = cat
    per_cat_counter[cat] += 1

# ----- 2) Select just your 40 docs -----
selected_rows = []
selected_filenames = []
for gidx in indices:
    if gidx in global_to_filename:
        fname = global_to_filename[gidx]
        cat = global_to_category[gidx]
        selected_rows.append({"doc_id": gidx, "target_name": cat, "filename": fname})
        selected_filenames.append(fname)
    else:
        print(f"Warning: global index {gidx} not present in this dataset/subset/categories.")

details_df = pd.DataFrame(selected_rows).sort_values("doc_id").reset_index(drop=True)
print("\nDetailed Selected Docs (mapping):")
print(details_df)

# ----- 3) Load those files (only those 40), if they exist -----
loaded = []
missing = []
for fname in selected_filenames:
    path = os.path.join(processed_docs_dir, fname)
    if os.path.exists(path):
        loaded.append(fname)
    else:
        missing.append(fname)

print(f"\nFound {len(loaded)} / {len(selected_filenames)} processed files.")
if missing:
    print("Missing (create or re-process these to match your selection):")
    for m in missing:
        print("  -", m)

# ----- 4) Class distribution for the loaded subset -----
from collections import defaultdict
cat_to_files = defaultdict(list)
for fname in loaded:
    cat = fname.split("_doc")[0]
    cat_to_files[cat].append(fname)

class_distribution = pd.DataFrame(
    [{"Category": c, "Count": len(v), "Filenames": v} for c, v in sorted(cat_to_files.items())]
).reset_index(drop=True)

print("\nClass distribution in selected documents:")
print(class_distribution)

Building global_index -> filename mapping from sklearn order...

Detailed Selected Docs (mapping):
    doc_id            target_name  \
0        0     rec.sport.baseball
1        2  talk.politics.mideast
2        4              sci.space
3        6            alt.atheism
4        8            alt.atheism
5       10     rec.sport.baseball
6       12  talk.politics.mideast
7       14              sci.space
8       16          comp.graphics
9       18          comp.graphics
10      20  talk.politics.mideast
11      22     rec.sport.baseball
12      24  talk.politics.mideast
13      26     rec.sport.baseball
14      28              sci.space
15      30            alt.atheism
16      32            alt.atheism
17      34     rec.sport.baseball
18      36     rec.sport.baseball
19      38     rec.sport.baseball
20      40  talk.politics.mideast
21      42  talk.politics.mideast
22      44              sci.space
23      46              sci.space
24      48          comp.graphics
25      50     rec.sport.baseball
26      52     rec.sport.baseball
27      54              sci.space
28      56            alt.atheism
29      58     rec.sport.baseball
30      60  talk.politics.mideast
31      62  talk.politics.mideast
32      64  talk.politics.mideast
33      66              sci.space
34      68          comp.graphics
35      70          comp.graphics
36      72     rec.sport.baseball
37      74              sci.space
38      76            alt.atheism
39      78            alt.atheism

                                        filename
0      rec.sport.baseball_doc0000_processed.json
1   talk.politics.mideast_doc0000_processed.json
2               sci.space_doc0000_processed.json
3             alt.atheism_doc0001_processed.json
4             alt.atheism_doc0002_processed.json
5      rec.sport.baseball_doc0002_processed.json
6   talk.politics.mideast_doc0001_processed.json
7               sci.space_doc0004_processed.json
8           comp.graphics_doc0001_processed.json
9           comp.graphics_doc0002_processed.json
10  talk.politics.mideast_doc0003_processed.json
11     rec.sport.baseball_doc0003_processed.json
12  talk.politics.mideast_doc0006_processed.json
13     rec.sport.baseball_doc0004_processed.json
14              sci.space_doc0007_processed.json
15            alt.atheism_doc0006_processed.json
16            alt.atheism_doc0007_processed.json
17     rec.sport.baseball_doc0005_processed.json
18     rec.sport.baseball_doc0006_processed.json
19     rec.sport.baseball_doc0008_processed.json
20  talk.politics.mideast_doc0008_processed.json
21  talk.politics.mideast_doc0009_processed.json
22              sci.space_doc0009_processed.json
23              sci.space_doc0010_processed.json
24          comp.graphics_doc0006_processed.json
25     rec.sport.baseball_doc0012_processed.json
26     rec.sport.baseball_doc0014_processed.json
27              sci.space_doc0012_processed.json
28            alt.atheism_doc0009_processed.json
29     rec.sport.baseball_doc0018_processed.json
30  talk.politics.mideast_doc0010_processed.json
31  talk.politics.mideast_doc0011_processed.json
32  talk.politics.mideast_doc0012_processed.json
33              sci.space_doc0015_processed.json
34          comp.graphics_doc0008_processed.json
35          comp.graphics_doc0009_processed.json
36     rec.sport.baseball_doc0020_processed.json
37              sci.space_doc0016_processed.json
38            alt.atheism_doc0012_processed.json
39            alt.atheism_doc0013_processed.json

Found 40 / 40 processed files.

Class distribution in selected documents:
                Category  Count  \
0            alt.atheism      7
1          comp.graphics      5
2     rec.sport.baseball     11
3              sci.space      8
4  talk.politics.mideast      9

                                           Filenames
0  [alt.atheism_doc0001_processed.json, alt.athei...
1  [comp.graphics_doc0001_processed.json, comp.gr...
2  [rec.sport.baseball_doc0000_processed.json, re...
3  [sci.space_doc0000_processed.json, sci.space_d...
4  [talk.politics.mideast_doc0000_processed.json,...

# pracitce

## Manual Preparation

In [45]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups

# Step 1: Choose 5 categories
chosen_categories = ['comp.graphics', 'sci.space', 'rec.sport.baseball', 
                     'talk.politics.mideast', 'alt.atheism']

# Step 2: Load dataset with only those categories
data = fetch_20newsgroups(
    subset='train',
    categories=chosen_categories,
    remove=('headers', 'footers', 'quotes')
)

# Step 3: Build a DataFrame with doc IDs
df = pd.DataFrame({
    'doc_id': range(len(data.data)),  # assign doc IDs
    'text': data.data,
    'target': data.target,
    'target_name': [data.target_names[i] for i in data.target]
})


# ✅ Example: manually chosen doc IDs (must exist in df)
selected_doc_ids = [
    0,  2,  4,  6,  8,
    10, 12, 14, 16, 18,
    20, 22, 24, 26, 28,
    30, 32, 34, 36, 38,
    40, 42, 44, 46, 48,
    50, 52, 54, 56, 58,
    60, 62, 64, 66, 68,
    70, 72, 74, 76, 78
]



# Step 4: Filter DataFrame by chosen doc IDs
selected_df = df[df['doc_id'].isin(selected_doc_ids)].copy()

# Step 5: Add snippet for readability
selected_df['snippet'] = selected_df['text'].str.slice(0, 200)


# ✅ Step 6: Class distribution with doc_ids
class_distribution = (
    selected_df.groupby('target_name')['doc_id']
    .apply(list)
    .reset_index(name='doc_ids')
)
class_distribution['Count'] = class_distribution['doc_ids'].apply(len)

# Display detailed selected docs
print("Detailed Selected Docs")
display(selected_df[['doc_id', 'target_name', 'snippet']])

# Display class distribution
print("\nClass distribution in selected documents:")
display(class_distribution[['target_name', 'doc_ids', 'Count']])

Detailed Selected Docs

,doc_id,target_name,snippet
0,0,talk.politics.mideast,"\n(forgive any inaccuracies, i deleted the ori..."
2,2,comp.graphics,Hi!\n\tI am working on a project that needs to...
4,4,talk.politics.mideast,"\n\n\nIs this the same Monolithic, Centrally C..."
6,6,comp.graphics,I am working on a project where we are going t...
8,8,rec.sport.baseball,\n\nAre you for real? How many Gold Gloves do...
10,10,sci.space,Please get a REAL life.\n\n
12,12,talk.politics.mideast,Accounts of Anti-Armenian Human Right Violatio...
14,14,comp.graphics,
16,16,comp.graphics,\nI certainly do use it whenever I have to do ...
18,18,rec.sport.baseball,"\n\tOh, yeah. Dave Winfield--marginal player...."
20,20,sci.space,"\n\n\n\n\n\nWell, I guess I'm left wondering j..."
22,22,comp.graphics,To: ad994@Freenet.carleton.ca\n\nJW> 1) Where ...
24,24,comp.graphics,"Hello,\n\n I have been searching for a qual..."
26,26,rec.sport.baseball,"\n\nI don't have a history handy, but I don't ..."
28,28,sci.space,\n\n\n\nCareful. Making statements about how ...
30,30,comp.graphics,I aparantly mistyped the address for the ftp s...
32,32,rec.sport.baseball,"\n\nAs far as I know, Toronto, Pittsburgh, and..."
34,34,talk.politics.mideast,"\nI don't, though when I was in Israel I did m..."
36,36,talk.politics.mideast,"\n\nDorin, of all the criticism of my post exp..."
38,38,rec.sport.baseball,"MLB Standings and Scores for Thursday, April 1..."
40,40,alt.atheism,\n\nNot so. If you are thrown into a cage wit...
42,42,sci.space,Has anyone heard of or Played Buzz Aldrin's Ra...
44,44,rec.sport.baseball,Is there any doubt that this is true? After a...
46,46,sci.space,"\nThe General Chairman is Paul Bialla, who is ..."
48,48,comp.graphics,"Organization: ""A World of Information at your ..."
50,50,comp.graphics,Hi!... \n\nI am searching for packages that co...
52,52,alt.atheism,"\n: Mr Connor's assertion that ""more complex"" ..."
54,54,comp.graphics,We are interested in purchasing a grayscale pr...
56,56,alt.atheism,"\nIf you force me to do something, am I morall..."
58,58,sci.space,I am doing a political science paper on the fu...
60,60,talk.politics.mideast,\n\n\n\nSo I should be very comfortable that 5...
62,62,sci.space,A brief political/cultural item.\n\nRadio stat...
64,64,alt.atheism,[most of post deleted]\nThere is an easy way o...
66,66,sci.space,\n\nToo bad they didn't give him a tour of th...
68,68,talk.politics.mideast,"\n\nHehehe.\n\nBTW, does the Litani River not ..."
70,70,comp.graphics,WHATS THIS 680x1024 256 color mode? Asking a ...
72,72,rec.sport.baseball,The Red Sox usually have 2 catchers. I don't ...
74,74,alt.atheism,"\n\nBut, you wouldn't know what red *was*, and..."
76,76,talk.politics.mideast,Accounts of Anti-Armenian Human Right Violatio...
78,78,comp.graphics,/*\n\nThis program doesn't detect edges with c...

Class distribution in selected documents:

,target_name,doc_ids,Count
0,alt.atheism,"[40, 52, 56, 64, 74]",5
1,comp.graphics,"[2, 6, 14, 16, 22, 24, 30, 48, 50, 54, 70, 78]",12
2,rec.sport.baseball,"[8, 18, 26, 32, 38, 44, 72]",7
3,sci.space,"[10, 20, 28, 42, 46, 58, 62, 66]",8
4,talk.politics.mideast,"[0, 4, 12, 34, 36, 60, 68, 76]",8

In [54]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups

# Step 1: Choose 5 categories
chosen_categories = [
    'comp.graphics', 
    'sci.space', 
    'rec.sport.baseball', 
    'talk.politics.mideast', 
    'alt.atheism'
]

# Step 2: Load dataset
data = fetch_20newsgroups(
    subset='train',
    categories=chosen_categories,
    remove=('headers', 'footers', 'quotes')
)

# Step 3: Build DataFrame
df = pd.DataFrame({
    'doc_id': range(len(data.data)),
    'text': data.data,
    'target': data.target,
    'target_name': [data.target_names[i] for i in data.target]
})

# ✅ Step 4: Select first 100 per category (to mimic your local processing)
selected_df = (
    df.groupby('target_name', group_keys=False)
      .apply(lambda x: x.iloc[:40])   # first 100 per category
      .reset_index(drop=True)
)

# Step 5: Add snippet for readability
selected_df['snippet'] = selected_df['text'].str.slice(0, 200)

# Step 6: Class distribution
class_distribution = (
    selected_df.groupby('target_name')['doc_id']
    .apply(list)
    .reset_index(name='doc_ids')
)
class_distribution['Count'] = class_distribution['doc_ids'].apply(len)

# Display results
print("Detailed Selected Docs")
display(selected_df[['doc_id', 'target_name', 'snippet']])

print("\nClass distribution in selected documents:")
display(class_distribution[['target_name', 'doc_ids', 'Count']])

Detailed Selected Docs

C:\Users\DELL\AppData\Local\Temp\ipykernel_13504\1735369516.py:31: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.iloc[:40])   # first 100 per category

,doc_id,target_name,snippet
0,3,alt.atheism,"\nOf course, the list has to agree with the ni..."
1,19,alt.atheism,\nProbably we would have much the same problem...
2,33,alt.atheism,\n:> God is eternal. [A = B]\n:> Jesus is G...
3,40,alt.atheism,\n\nNot so. If you are thrown into a cage wit...
4,45,alt.atheism,"\n\nBut, the goal need not be a subjective one..."
...,...,...,...
195,142,talk.politics.mideast,"\n\nI didnot know that ""Master of wisdom"" can ..."
196,143,talk.politics.mideast,"It's irritating when someone mis-labels ""us"" a..."
197,150,talk.politics.mideast,The Armenians were deeply anti-semitic as well...
198,157,talk.politics.mideast,\n\nThe fascist x-Soviet Armenian Government a...
199,158,talk.politics.mideast,\n# Well said Mr. Beyer :)\n\nHe-he. The great...

Class distribution in selected documents:

,target_name,doc_ids,Count
0,alt.atheism,"[3, 19, 33, 40, 45, 52, 53, 56, 64, 74, 83, 92...",40
1,comp.graphics,"[2, 6, 14, 16, 21, 22, 24, 25, 27, 30, 41, 48,...",40
2,rec.sport.baseball,"[5, 8, 9, 15, 18, 23, 26, 31, 32, 37, 38, 43, ...",40
3,sci.space,"[10, 20, 28, 35, 39, 42, 46, 57, 58, 62, 66, 8...",40
4,talk.politics.mideast,"[0, 1, 4, 7, 11, 12, 13, 17, 29, 34, 36, 47, 6...",40